name: MeshCommander
version: "1.1.9"
slug: meshcommander
description: Run MeshCommander in Home Assistant
arch:
  - amd64
  - armv7
  - armhf
  - aarch64
startup: application
boot: auto
ingress: true
ingress_port: 3000
#options:
#  debug: false
#schema:
#  debug: bool
# init: "false"
# webui: "http://[HOST]:[PORT:3000]"

