name: MeshCentral
version: "0.0.1d4"
slug: meshcentral
description: Run MeshCentral in Home Assistant
arch:
  - amd64
  - armv7
  - armhf
  - aarch64
startup: application
boot: auto
#ports:
#  3000/tcp: 3000
ingress: true
ingress_port: 80
options:
  debug: false
  hostname: "local"
  allow_new_accounts: false
  webrtc: true
  backups_pw: "secret"
  backup_interval: 7
  backup_keep_days: 70
schema:
  debug: bool
  hostname: str
  allow_new_accounts: bool
  webrtc: bool
  backups_pw: str
  backup_interval: int
  backup_keep_days: int
init: false
webui: "http://[HOST]:[PORT:80]"

