name: MeshCentral
version: "0.0.1a47"
slug: meshcentral
description: Run MeshCentral in Home Assistant
arch:
  - amd64
  - armv7
  - armhf
  - aarch64
startup: application
boot: auto
ports:
  11180/tcp: 11180
network:
  11180/tcp: "The port to be used for agents."
map:
  addon_config:
    read_only: false
  share:
    read_only: false
ingress: true
ingress_port: 80
hassio_api: true
hassio_role: "default"
options:
  debug: false
  hostname: "local"
  allow_new_accounts: false
  webrtc: true
  backups_pw: "secret"
  backup_interval: 7
  backup_keep_days: 70
  session_key:
schema:
  debug: "bool"
  hostname: "str"
  allow_new_accounts: "bool"
  webrtc: "bool"
  backups_pw: "str"
  backup_interval: "int"
  backup_keep_days: "int"
  session_key: "str?"
init: false
# webui: "http://[HOST]:[PORT:80]"

