name: MeshCentral
version: "0.0.1a21"
slug: meshcentral
description: Run MeshCentral in Home Assistant
arch:
  - amd64
  - armv7
  - armhf
  - aarch64
startup: application
boot: auto
ports:
  1234/tcp: 1234
ports_description:
  1234/tcp: "The port to be used for agents calling in to the plugin"
map:
  - share:rw
  - addon_config:rw
ingress: true
ingress_port: 80
ingress_stream: true
hassio_api: true
hassio_role: "default"
panel_admin: true # Make the menu entry only available to users in the admin group.
options:
  debug: false
  hostname: "hass.local"
  allow_new_accounts: false
  webrtc: true
  backups_pw: "secret"
  backup_interval: 7
  backup_keep_days: 70
  session_key: ""
schema:
  debug: bool
  hostname: str
  allow_new_accounts: bool
  webrtc: bool
  backups_pw: str
  backup_interval: int
  backup_keep_days: int
  session_key: "str?"
init: false
# webui: "http://[HOST]:[PORT:80]"

